name: verify

on:
  schedule:
      - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wgcf register
        run: |
          mkdir -p /tmp/wgcf
          pushd /tmp/wgcf
          docker run --rm -id --name wgcf -v /tmp/wgcf:/wgcf -w /wgcf -p 1080:1080 ubuntu:latest
          docker exec -i wgcf apt-get update
          docker exec -i wgcf apt-get install -y wget ca-certificates
          docker exec -i wgcf wget -O wgcf https://github.com/ViRb3/wgcf/releases/download/v2.2.21/wgcf_2.2.21_linux_amd64
          docker exec -i wgcf chmod +x wgcf
          docker exec -i wgcf ./wgcf register --accept-tos
          docker exec -i wgcf ./wgcf generate
          export WIREGUARD_PUBLIC_KEY="$(docker exec -i wgcf cat wgcf-profile.conf | sed -E 's/[ \t]//g' | grep -oP '(?<=PublicKey=)[^\n]+')"
          [ -n "$WIREGUARD_PUBLIC_KEY" ]
          export WIREGUARD_PRIVATE_KEY="$(docker exec -i wgcf cat wgcf-profile.conf | sed -E 's/[ \t]//g' | grep -oP '(?<=PrivateKey=)[^\n]+')"
          [ -n "$WIREGUARD_PRIVATE_KEY" ]
          docker kill wgcf
          popd
          cp .env.sample .env
          sed -i "s@WIREGUARD_PUBLIC_KEY=@WIREGUARD_PUBLIC_KEY=$WIREGUARD_PUBLIC_KEY@" .env
          sed -i "s@WIREGUARD_PRIVATE_KEY=@WIREGUARD_PRIVATE_KEY=$WIREGUARD_PRIVATE_KEY@" .env
      - name: run
        run: |
          docker compose up --abort-on-container-exit --exit-code-from app
      - name: commit
        run: |
          sudo chown `id -u`:`id -g` good.json
          go run .

          git config user.name dependabot[bot]
          git config user.email 49699333+dependabot[bot]@users.noreply.github.com
          git add -f good.json
          git commit -m 'update' || exit 0
          git branch -M result
          git push -f -u origin result
